version: '3.8'

services:
  hotel-catalog-admin:
    container_name: hotel-catalog-admin
    image: hotel-catalog-admin
    restart: always
    env_file: .env.local
    build: .
    command: ./docker-entrypoint.sh
    networks:
      - hotel-catalog-admin
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
    hotel-catalog-admin:
      name: 'hotel-catalog-admin'
