"""
Django settings for hotel_catalog_admin project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3xr%v&4t1hkb0#aud+yw-l0m=)7ay*z(#8=aujfpdr)_4b6nxd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.User'
AUTH_USER_USERNAME_FIELD = 'email'
AUTH_JWT_ALGORITHM = 'HS256'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'users',
    'hotels',
    'references',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hotel_catalog_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel_catalog_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '108385442871730998734',
            'secret': '-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC78eQUz1xb44Qi\nO11fvSkCpI9imZidnZ+mH1/xtj93Um5s/SSkR4oeZz5PPh9W4Ox9GzyIsu7oUJ+n\nFdB7430sR2a3pDQHtce4w6XzlFRgnRgAS90V6Y4qyKqX/GfXwfFIX1DwimwxlFvg\neyg5vaLvKyO1zql3qSgX6LmrbrgXsy9HOn4BnPLBREcSc223xOk3O1fyuZYMnCFn\nxJnYFf/AzHvJ0vwTI1m4U68smcD2FjziO/3+5L+DYrwc4wGDy/vMhmMY7uf7I9p2\nFVjYSP4xlNZ9508OOo4gUUrVeU3i9yiFE5Orak+cWgnv0yCaW/4UpGdkHm5tlEaK\np/5g67qnAgMBAAECggEAEqo0oP5w6S1Ap5emr8Xc50bJeJzRY8HOI5TVFe+oAOUe\nU1OWinwSUu+k6AC+4wVmZwxH6DmA8XBkUpcfg9Y1TarvoAg+JI/gfFBt0DFoacng\nItNl6vGtbUFNc9ecxngbyriwlJrioM/fif0hIw7aug7aNomGGfyiHzG9ErHltXCp\n5zTmH0kmqoEicogpDMBdToxyPxsa1of0Xeed8jAZbbCWT2hp87Beep/U83Tb1YVB\n+EK3oWZSRsw22DPXNCq1JrxFihlMQc+68rz6iSkFA6BrUmC7K1oNT0ODYtaSejIp\nlUcAPRTBFXMOtcWrExv804T3eYjtarZ8uOQXc8FQNQKBgQDuSH4/iKVczjba7FIa\nmUlFGlDXXXbUSsSq3U4H79EKi32szuasCZs31oBf84lI81lv8vx2VnpRH+iM1bcc\nLaWwJuqx4q4wrfNYIt7aI6Obf3//N/RT4dd75CJOHee4ZVX4h9KvDCGxp/ehoSuG\nUz9QuNOn1ZqoWKIqaR/IcRoz2wKBgQDJ60Dm49MbKi+LvyHLIMmOzDvU6U1M5JnF\n4aVSw/uTxMFdzJRtnJsGfKDrstjrPfMy3aOjG5rX6jGb/4nYyfg5TNsbLjw30YG9\n1l9K1uIl/7A6idsVmh4sPdeuaRnDPo2qzzr5CGvpfGmjc43TZfdpWe+BzbUUbZEy\nC1sA3Nl0JQKBgDLn19jY54MBJyT0EcJO9yFFMvofpJBL/OIH73Cwojcff9TYSt18\nG+X89GYLUEv+eR/6iEb7yJvmNjdIPRtPATO1zLP+GnqZ3v/4SyXNMVm6Dm1G1fLJ\nr9Bu94k6yFNTit9SnQb6j4Q1vyiPlw3WYRNsuQMFFkpazSJEXR7kUtW7AoGBALMN\nRUE5d6MYFo9ijtH0oidZnhjgRWbRNDcQMC0jkzxm9l16I4jLnYD0FTLNJqP8DGPn\nvMrPmNCsYQ+HW7J87vvI1mbU6htJUjaIGXpg8Ktnf9t5EWingOgUcuS7WFgVaUS1\nfQMGX8LtSzPhLTvvqKSoVsWRJ2kU+/MXtLwgG0htAoGAPF3YoUNKGCYdFr1xf1sZ\nIpMZXjtfGhFkHHP/ZQdOu6N1LMnRiI5TP1RCqjtaKnbF5rjc82WlwG/wVxodpujI\n+8tu/n+HJlMk2tVWxoq0hJHFSD9L4KgXnfM5DzlQBjzH2yFWGG8w5IzJzNybJ6ZA\nmIcCFv3LWQQKuuazV2vIJKw=\n-----END PRIVATE KEY-----\n',
            'key': '8c37daace18694cf06e73c57fd948982fc208e6e'
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.TokenAuthentication',
        'users.jwt_auth.JWTAuthentication',
    )
}





